### ISSUE TITLE
AWS Region Failure for API Endpoint

### ISSUE THREAD

**Issue by nata-1** [ashirt-ops/ashirt-deployments#12]
ECS API Task Exception:

```text
Upload to s3 failed : MissingRegion: could not find region configuration" rootError="Unable to upload evidence : Upload to s3 failed : MissingRegion: could not find region configuration" status=500 url=/api/operations/test/evidence
```
This only happens when attempting to upload evidence from the Ashirt Client and not from the WebUI. The WebUI works fine. 

## Attempted to Patch

1. Made sure we have default region set for all ECS containers/tasks. That did not seem to do anything.

## Checking the current config:

- `aws ecs describe-task-definition --task-definition post-api:2 --region us-east-1`

```json
"environment": [
                    {
                        "name": "AWS_DEFAULT_REGION",
                        "value": "us-east-1"
                    }
                ],
                "environmentFiles": [
                    {
                        "value": "arn:aws:s3:::post-ashirt-env/app/.env",
                        "type": "s3"
                    },
                    {
                        "value": "arn:aws:s3:::post-ashirt-env/db/.env",
                        "type": "s3"
                    }
                ],
```

**Comment by jkennedyvz** [comment]
Hi @nata-1 are you still experiencing this issue?

**Comment by jkennedyvz** [comment]
I'm unable to reproduce. If you're still experiencing issues please ask for help in our discord. https://discord.gg/swhtf96Dsm
